version: '3.8'

services:
  app:
    build: .
    container_name: auth_product
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - JWT_SECRET=secretKey
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    volumes:
      - .:/usr/src/app

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: auth_product_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning

volumes:
  postgres_data: